apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deploy
  labels:
    app: react
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: reactjs
        image: manojmanoj1122334455/reactjs:v4
        ports:
        - containerPort: 80
